spring:
  profiles:
    active: dev
server:
  port: 8888
---
server:
  port: 1101
spring:
  profiles: dev
  application:
    name: microservice-config-dev
---
server:
  port: 1102
spring:
  profiles: prod
  application:
    name: microservice-config-prod
