spring:
  profiles:
    active: prod
---
server:
  port: 8912
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.jinlong.springcloud.entities # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件
spring:
  profiles: dev
  application:
    name: mat-bus
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://10.255.128.4:3306/jinlong_test1?serverTimezone=GMT%2B8 # 数据库名称
    username: root
    password: root@123
    dbcp2:
    min-idle: 5 # 数据库连接池的最小维持连接数
    initial-size: 5 # 初始化连接数
    max-total: 5 # 最大连接数
    max-wait-millis: 150 # 等待连接获取的最大超时时间
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka6002:6002/eureka/,http://eureka6001:6001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}   #指定实例ID,就不会显示主机名称
    prefer-ip-address: true
---
server:
  port: 8012
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.jinlong.springcloud.entities # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件
spring:
  profiles: prod
  application:
    name: microservice-mat #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://10.255.128.4:3306/jinlong_test1?serverTimezone=GMT%2B8 # 数据库名称
    username: root
    password: root@123
    dbcp2:
    min-idle: 5 # 数据库连接池的最小维持连接数
    initial-size: 5 # 初始化连接数
    max-total: 5 # 最大连接数
    max-wait-millis: 150 # 等待连接获取的最大超时时间
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka6002:6002/eureka/,http://eureka6001:6001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port} #指定实例ID,就不会显示主机名称
    prefer-ip-address: true
group:
  name: xyd
